### ISSUE TITLE
encription/decription not consistant

### ISSUE THREAD

**Issue by toonamo** [qistoph/ArduinoAES256#3]
The library works great on a single processor. However if you encrypt the same string with the same keys, each processor (a duo and a pro mini), will generate a slightly different encrypted data array. 

Is there something I am missing, or can do in order to "sync" the encription/ decription across multiple processors on a i2c bus?

**Comment by qistoph** [comment]
Both should generate the same results. You could try the AES test vectors to see which one is malfunctioning.

See Appendix C.3 in http://csrc.nist.gov/publications/fips/fips197/fips-197.pdf

**Comment by qistoph** [comment]
No reply. Closing
