### ISSUE TITLE
RAM and Flash requirements

### ISSUE THREAD

**Issue by KarlZeilhofer** [qistoph/ArduinoAES256#4]
Hi, is there some data available about the memory usage of this nice code?
Perhaps I want to use it on an ATmega328p with 32k flash and 2k RAM. 
Thanks in advance, Karl

**Comment by qistoph** [comment]
Hi Karl, sorry for the late reply.

I don't have a memory profile ready for you, but I have used the code on the Arduino Duemilanove which uses an ATmega328p.
